### ISSUE TITLE
How can I build and run it?

### ISSUE THREAD

**Issue by trappedinspacetime** [MyLittleRobo/mimeapps#2]
I am running Ubuntu 16.04 32 bit. I installed `dub` then cloned `mimeapps` repository. I don't know how to build and run it.  

        dub examples/test.d

above example command fails with 
        
         Unknown command: examples/test.d

**Comment by FreeSlave** [comment]
That's weird. What's your dub version? Try `dub --single examples/test.d`

**Comment by trappedinspacetime** [comment]
@FreeSlave Thank you for responding
 `DUB version Version: 0.9.24-2, built on Apr 16 2016`

      dub --single examples/test.d
      Unknown command line flags: --single
      Type "dub run -h" to get a list of all supported flags.

**Comment by FreeSlave** [comment]
@trappedinspacetime probably your dub version is too old and does not support single-file projects. Did you get it from ubuntu repositories?
You can rework single-file into a separate project, but if you get stuff from reps, your compiler is probably too old to support this codebase anyway.

**Comment by trappedinspacetime** [comment]
I installed it from official Ubuntu repo. I think it's obsolete for your project.

**Comment by trappedinspacetime** [comment]
I want to build and install latest version of `dub` from source, but I didn't find any source or documentation about how to do that.
